require('impatient')
require 'user.settings'
require 'user.keymaps'
require 'user.comment'
require 'user.completion'
require 'user.treesitter'
require 'user.lsp'
require 'user.neoclip'
require 'user.telescope'
require 'user.toggleterm'
require 'user.gitsigns'
require 'user.feline'
require 'user.bufferline'
require 'user.nvim-tree'
require 'user.autopairs'
require 'user.project'
-- require 'user.diffview'
-- require 'user.neogit'
require 'user.hop'
require 'user.colorizer'
require 'user.scrollbar'
-- require 'user.whichkey'
